name: Download File and Commit

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download file
        run: curl -L -o ./sample1.txt https://filesampleshub.com/download/document/txt/sample1.txt

      - name: Commit changes
        run: |
          git config --global user.name 'nooglersoon'
          git config --global user.email 'nooglersoon@outlook.co.id'
          git add ./sample1.txt
          git commit -m "Add downloaded file"
          git push
