name: Download File and Commit

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download file
        run: curl -L -o ./sample1.txt https://filesampleshub.com/download/document/txt/sample1.txt

      - name: Configure Git
        run: |
          git config --global user.name 'nooglersoon'
          git config --global user.email 'nooglersoon@outlook.co.id'

      - name: Add and Commit Changes
        run: |
          git add ./sample1.txt
          git commit -m "Add downloaded file"

      - name: Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_SECRETS }}
        run: |
          git remote set-url origin https://${{ secrets.PAT_SECRETS }}@github.com/nooglersoon/pastebar.git
          git push origin HEAD:main
